### PR TITLE
Update for breaking changes in 0.15

### PR DESCRIPTION
**Pull request by lenganley**
I've only been playing with Elm for a couple of days, so may not have fixed the issues in the best way, but it works. (I've only been playing with github for one day, so let's see if this works too...)

### CODE REVIEW

**Comment by theburningmonk** [comment]
awesome, thanks for doing this!

**Comment by lenganley** [comment]
No problem, it was a great way to test what I'd learnt about Elm. Thanks
for making your code available!

Michael

**Comment by theburningmonk** [comment]
I made some subsequent changes to make it work with the version elm-make in
the 0.15 release, some things seem to have changed - e.g. name of the
dependency yml, etc.

If you pull from the latest on develop you should see those now, and I
generated `main.html` from elm-make (something I should probably have done
in the past so the output is locked onto that particular version of elm it
was built with) so the demo shouldn't break when new versions of elm
becomes available.

**Comment by lenganley** [comment]
Excellent! I was kind of working blind there as I was using the online
compiler -- I'd not realised how easy Elm was to install. I've since
installed it, and worked out a bit more about how to use Git so your
changes will be very helpful.

**Pull request merged**
